<a href="https://colab.research.google.com/github/kevinptx/CWCT-Machine-Learning-Foundation/blob/main/ML_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
hwd=np.loadtxt("./lab2-hw.txt", dtype=str)
testd=np.loadtxt("./lab2-test.txt", dtype=str)
quizd=np.loadtxt("./lab2-quiz.txt", dtype=str)
projd=np.loadtxt("./lab2-project.txt", dtype=str)

In [6]:
print(hwd)

[['Name' 'hw1' 'hw2' 'hw3' 'hw4' 'hw5']
 ['A' '45' '46' '50' '39' '50']
 ['B' '35' '40' '41' '45' '40']
 ['C' '31' '38' '40' '29' '45']
 ['D' '40' '41' '42' '45' '41']
 ['E' '49' '47' '41' '39' '45']
 ['F' '30' '31' '38' '40' '39']]


In [8]:
hw = (hwd[1:, 1:]).astype(float)

In [10]:
test = (testd[1:, 1:]).astype(float)
quiz = (quizd[1:, 1:]).astype(float)
proj = (projd[1:, 1:]).astype(float)

In [12]:
hw_ave = np.average(hw, axis=1)

In [13]:
print(hw_ave)

[46.  40.2 36.6 41.8 44.2 35.6]


In [14]:
test_ave = np.average(test, axis=1)
quiz_ave = np.average(quiz, axis=1)
proj_ave = np.average(proj, axis=1)

In [15]:
print(test_ave)

[94.  90.  83.  87.5 74.5 80. ]


In [16]:
hw_w = hw_ave*(100/50)

In [17]:
print(hw_w)

[92.  80.4 73.2 83.6 88.4 71.2]


In [18]:
test_w = test_ave*(100/100)
quiz_w = quiz_ave*(100/10)
proj_w = proj_ave*(100/100)

In [20]:
grades = np.column_stack((hw_w, test_w, quiz_w, proj_w))

In [21]:
print(grades)

[[92.  94.  90.  90. ]
 [80.4 90.  88.  95. ]
 [73.2 83.  80.  85. ]
 [83.6 87.5 94.  71. ]
 [88.4 74.5 88.  82. ]
 [71.2 80.  76.  70. ]]


In [22]:
wgt = [0.3, 0.4, 0.1, 0.2]

In [23]:
final_grade = np.matmul(grades, wgt)

In [24]:
print(final_grade)

[92.2  87.92 80.16 83.68 81.52 74.96]


In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_pickle('lab2-T2-data.pkl')

In [26]:
df.head(3)

title subtitle series  \
0                                           "13 1/2"      NaN    NaN   
1  "The Secret Diary of Hendrik Groen, 83 1/2 Yea...      NaN    NaN   
2                            18 and Life on Skid Row      NaN    NaN   

            author my_rating avg_rating                 publisher    binding  \
0     Barr, Nevada       3.0        3.3            Vanguard Press  Hardcover   
1   Groen, Hendrik       4.0       3.95  Grand Central Publishing  Hardcover   
2  Bach, Sebastian       3.0       3.68          Dey Street Books  Hardcover   

   pages year_published month_read  month_read_num  year_read bookshelf  
0    320           2009        May               5       2011      read  
1    384           2014     August               8       2017      read  
2    433           2016      April               4       2020      read

In [27]:
print(df.shape)

(671, 14)


In [28]:
print(df.columns)

Index(['title', 'subtitle', 'series', 'author', 'my_rating', 'avg_rating',
       'publisher', 'binding', 'pages', 'year_published', 'month_read',
       'month_read_num', 'year_read', 'bookshelf'],
      dtype='object')


In [30]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   title           671 non-null    object
 1   subtitle        218 non-null    object
 2   series          122 non-null    object
 3   author          671 non-null    object
 4   my_rating       640 non-null    object
 5   avg_rating      671 non-null    object
 6   publisher       669 non-null    object
 7   binding         671 non-null    object
 8   pages           671 non-null    int64 
 9   year_published  671 non-null    object
 10  month_read      671 non-null    object
 11  month_read_num  671 non-null    int64 
 12  year_read       671 non-null    int64 
 13  bookshelf       671 non-null    object
dtypes: int64(3), object(11)
memory usage: 73.5+ KB
None


In [31]:
print(df.dtypes)

title             object
subtitle          object
series            object
author            object
my_rating         object
avg_rating        object
publisher         object
binding           object
pages              int64
year_published    object
month_read        object
month_read_num     int64
year_read          int64
bookshelf         object
dtype: object


In [32]:
print(np.sum([df.isnull()]))

1035


In [33]:
print(np.sum([df.my_rating.isnull()]))

31


In [34]:
for columns in df:
  print(columns)

title
subtitle
series
author
my_rating
avg_rating
publisher
binding
pages
year_published
month_read
month_read_num
year_read
bookshelf


In [35]:
for columns in df:
  #print(np.sum([df.isnull()]))
  print(columns,": ", np.sum(df[columns].isnull()))

title :  0
subtitle :  453
series :  549
author :  0
my_rating :  31
avg_rating :  0
publisher :  2
binding :  0
pages :  0
year_published :  0
month_read :  0
month_read_num :  0
year_read :  0
bookshelf :  0


In [36]:
for columns in df:
  #print(columns)
  print(columns,": ", df[columns].isnull().sum())

title :  0
subtitle :  453
series :  549
author :  0
my_rating :  31
avg_rating :  0
publisher :  2
binding :  0
pages :  0
year_published :  0
month_read :  0
month_read_num :  0
year_read :  0
bookshelf :  0


In [37]:
df1 = df[df.my_rating.notnull()]

In [39]:
print('df:', df.shape)
print('df1:', df1.shape)

df: (671, 14)
df1: (640, 14)


In [40]:
print(np.sum([df1.my_rating.isnull()]))

0


In [41]:
for columns in df1:
  #print(columns)
  print(columns,": ", df1[columns].isnull().sum())

title :  0
subtitle :  437
series :  519
author :  0
my_rating :  0
avg_rating :  0
publisher :  2
binding :  0
pages :  0
year_published :  0
month_read :  0
month_read_num :  0
year_read :  0
bookshelf :  0


In [43]:
print(df1.dtypes)

title             object
subtitle          object
series            object
author            object
my_rating         object
avg_rating        object
publisher         object
binding           object
pages              int64
year_published    object
month_read        object
month_read_num     int64
year_read          int64
bookshelf         object
dtype: object


In [44]:
df1.my_rating = df1.my_rating.astype(float)
df1.avg_rating = df1.avg_rating.astype(float)
df1.year_published = df1.year_published.astype(int)

<ipython-input-44-c1a5638a08df>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.my_rating = df1.my_rating.astype(float)
<ipython-input-44-c1a5638a08df>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.avg_rating = df1.avg_rating.astype(float)
<ipython-input-44-c1a5638a08df>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/

In [45]:
print(df1.dtypes)

title              object
subtitle           object
series             object
author             object
my_rating         float64
avg_rating        float64
publisher          object
binding            object
pages               int64
year_published      int64
month_read         object
month_read_num      int64
year_read           int64
bookshelf          object
dtype: object


In [46]:
df1.loc[df1.subtitle.isnull(), 'subtitle'] = " "

In [47]:
for columns in df1:
  #print(columns)
  print(columns,": ", df1[columns].isnull().sum())

title :  0
subtitle :  0
series :  519
author :  0
my_rating :  0
avg_rating :  0
publisher :  2
binding :  0
pages :  0
year_published :  0
month_read :  0
month_read_num :  0
year_read :  0
bookshelf :  0


In [48]:
df1.loc[df1.series.isnull(), 'series'] = " "
df1.loc[df1.publisher.isnull(), 'publisher'] = " "

In [49]:
for columns in df1:
  #print(columns)
  print(columns,": ", df1[columns].isnull().sum())

title :  0
subtitle :  0
series :  0
author :  0
my_rating :  0
avg_rating :  0
publisher :  0
binding :  0
pages :  0
year_published :  0
month_read :  0
month_read_num :  0
year_read :  0
bookshelf :  0


In [50]:
print(df1[df1.year_published < 0].title)

61                   Bad Dog
85                Calico Joe
122               Die Trying
169         Garden of Beasts
250               Life of Pi
461        The First Husband
491    The King of Methlehem
667     You Know You Love Me
Name: title, dtype: object


In [51]:
df1 = df1[df1.year_published > 0]

In [52]:
print(df1.shape)

(632, 14)


In [53]:
print(df1[df1.my_rating < 0].title)

Series([], Name: title, dtype: object)


In [54]:
print(df1[df1.my_rating > 5].title)

Series([], Name: title, dtype: object)


In [55]:
print(df1[df1.avg_rating < 0].title)

106         Dark Homecoming
115      Dear Mr. Knightley
182                 Gretzky
482    The Imperfectionists
669    You Know You Love Me
Name: title, dtype: object


In [56]:
df1 = df1[df1.avg_rating >= 0]

In [57]:
print(df1[df1.avg_rating <0].title)

Series([], Name: title, dtype: object)


In [58]:
print(df1.shape)

(627, 14)


In [59]:
print(df1[df1.avg_rating > 5].title)

135                 Dreyer's English
150              Family Resemblances
236    Last Night at Chateau Marmont
425          The Book of Lost Things
668             You Know You Love Me
Name: title, dtype: object


In [60]:
df1 = df1[df1.avg_rating <= 5]

In [61]:
print(df1[df1.avg_rating > 5].title)

Series([], Name: title, dtype: object)


In [62]:
print(df1.shape)

(622, 14)


In [63]:
group_author = df1.groupby('author')
group_author.count()
print(group_author['author'].count())

author
Abramowitz, Andy         1
Ackerley, J.R.           1
Adams, David             1
Adler, Joseph            1
Adler, Steven            1
                        ..
Zerby, Chuck             1
Zevin, Gabrielle         1
Ziegesar, Cecily von     7
Zlozower, Neil           1
de Hamel, Christopher    1
Name: author, Length: 452, dtype: int64


In [64]:
df_num = group_author['author'].count()
max = 0
max_author = ''
for author in df_num.index:
    #YOUR CODE HERE
    if df_num[author] > max:
      max = df_num[author]
      max_author = author
print(max_author, max)


Grisham, John 22


In [65]:
for author, subset in df1.groupby('author'):
    if author == max_author:
      print(author)
      for index, row in subset.iterrows():
        print(row['title'], end=', ')
        print(row['year_published'])

Grisham, John
A Time to Kill, 1989
Calico Joe, 2012
Ford County, 2008
Playing for Pizza, 2007
Rogue Lawyer, 2015
Sycamore Row, 2013
The Associate, 2009
The Brethren, 2000
The Broker, 2005
The Chamber, 1994
The Confession, 2010
The King of Torts, 2003
The Last Juror, 2004
The Litigators, 2011
The Partner, 1997
The Racketeer, 2012
The Rooster Bar, 2018
The Street Lawyer, 1998
The Summons, 2002
The Testament, 1999
The Whistler, 2016
Theodore Boone, 2010
